microcontrollers-rest-api/app/blueprints/details/__init__.py
from flask import Blueprint

details = Blueprint('details',
                    __name__,
                    # url_prefix='/details',
                    template_folder='templates')

from app.blueprints.details import views

microcontrollers-rest-api/app/blueprints/details/views.py
import flask_login

from app.blueprints.details import details
from app.blueprints.details.details_bp import DetailsBp


@details.route('/app_details/', methods=['GET'])
def app_details():
    """ Returns project details.
        Output keys: ProjectName, Version, RootDirectory, HostName.
    """
    return DetailsBp().app_details()


@details.route('/help/', methods=['GET'])
@details.route('/help/<method>/', methods=['GET'])
def help(method=None):
    """ Returns docs for given method or if not specified list of docs for all service methods.
        Input args: /method/.
        Output keys: api_methods: {<method_name>} or <method_name>.
    """
    return DetailsBp().help(method=method)


@details.route('/info/')
def info():
    return DetailsBp().info()


@details.route('/methods/')
def methods():
    return DetailsBp().methods()

microcontrollers-rest-api/app/blueprints/details/templates/details/details.html
{% extends "base.html" %}

{% block body %}
    <script>
      function getData() {
        fetch("{{url_for('details.app_details')}}")
          .then(response => response.json())
          .then(data => {
             const container = document.getElementById('data-container');
            container.innerHTML = `
            <div class="white_text">
                <li>
                    <h3>Project name:</h3>
                    <p> ${data["ProjectName"]} </p>
                </li>
                <li>
                    <h3>Version:</h3>
                    <p> ${data["Version"]} </p>
                </li>
                <li>
                    <h3>Root directory:</h3>
                    <p> ${data["RootDirectory"]} </p>
                </li>
                <li>
                    <h3>Hostname:</h3>
                    <p> ${data["HostName"]} </p>
                </li>
            </div>`;
          })
          .catch(error => {
            console.error(error);
          });
      }
      getData();
    </script>

    <h1>App details</h1>
    <ul id="data-container"></ul>
{% endblock %}

microcontrollers-rest-api/app/blueprints/details/templates/details/methods.html
{% extends "base.html" %}

{% block body %}
    <script>
      function getData() {
        fetch("{{url_for('details.help')}}")
          .then(response => response.json())
          .then(data => {
             const container = document.getElementById('data-container');
            container.innerHTML = '';
            const methodsArray = data["api_methods"];
            for (var key in methodsArray){
                const element = document.createElement('li');
                element.className = "white_text"
                element.innerHTML = `
                <div class="white_text">
                    <h3> ${key}:</h3>
                    <p> ${methodsArray[key]}</p>
                </div>

                `;
                container.appendChild(element);
            }
          })
          .catch(error => {
            console.error(error);
          });
      }
      getData();
    </script>

    <h1> Methods description </h1>
    <ul id="data-container"></ul>
{% endblock %}