advanced-rest-api/app/blueprints/hardware/__init__.py
from flask import Blueprint

hardware = Blueprint('hardware',
                     __name__,
                     # url_prefix='/hardware',
                     template_folder='templates')

from app.blueprints.hardware import views

advanced-rest-api/app/blueprints/hardware/views.py
import flask_login

from app.blueprints.hardware import hardware
from app.blueprints.hardware.hardware_class import HardwareClass


@hardware.route('/performance/', methods=['GET'])
@flask_login.login_required
def performance():
    """ Collects computer performance data.
        Output keys: cpu: {usage, freq}, disk: {usage, total, used, free}, virtual_memory: {total, free, available, used}.
    """
    return HardwareClass().performance()


@hardware.route('/stats/', methods=['GET'])
@flask_login.login_required
def stats():
    return HardwareClass().stats()

advanced-rest-api/app/blueprints/hardware/templates/hardware/stats.html
{% extends "base.html" %}

{% block src %}
 <script>
      function getData() {
        fetch("{{url_for('hardware.performance')}}")
          .then(response => response.json())
          .then(data => {
             const container = document.getElementById('data-container');
             const cpu = data["cpu"]
             const disk = data["disk"]
             const virtual = data["virtual_memory"]
            container.innerHTML = `
            <div class="white_text">
                <li>
                    <h3>CPU:  </h3>
                    <p>Usage: ${cpu["usage"]}</p>
                    <p>Freq: ${cpu["freq"]}</p>
                </li>
                <li>
                    <h3>Disk:  </h3>
                    <p>Usage: ${disk["usage"]}</p>
                    <p>Total: ${disk["total"]}</p>
                    <p>Free: ${disk["free"]}</p>
                    <p>Used: ${disk["used"]}</p>
                </li>
                <li>
                    <h3>Virtual memory:  </h3>
                    <p>Usage: ${virtual["usage"]}</p>
                    <p>Total: ${virtual["total"]}</p>
                    <p>Available: ${virtual["available"]}</p>
                    <p>Used: ${virtual["used"]}</p>
                </li>
            </div>
              `;
          })
          .catch(error => {
            console.error(error);
          });
      }
      getData();
      setInterval(function() {
        getData();
      }, 500);
</script>
{% endblock %}

{% block body %}
    <h1> Performance </h1>
    <ul id="data-container"></ul>
{% endblock %}