microcontrollers-rest-api/app/blueprints/user/__init__.py
from flask import Blueprint

user = Blueprint('user',
                 __name__,
                 # url_prefix='/user',
                 template_folder='templates')

from app.blueprints.user import views

microcontrollers-rest-api/app/blueprints/user/views.py
import flask_login

from app.blueprints.user import user
from app.blueprints.user.user_bp import UserBp


@user.route('/register/', methods=['GET', 'POST'])
def register():
    """ Allows to register new user.
        Input args: login, password, repeat_password.
    """
    return UserBp().register()


@user.route('/logout/', methods=['GET'])
@flask_login.login_required
def logout():
    """ Allows to log out from application. """
    return UserBp().logout()


@user.route('/protected/', methods=['GET'])
@flask_login.login_required
def protected():
    """ Returns currently logged users in service.
        Output keys: logged_user.
    """
    return UserBp().protected()


@user.route('/users/<int:user_id>/', methods=['GET'])
@user.route('/users/', methods=['GET'])
def users(user_id: int = None):
    """ Returns user with given id or if not specified list of all users from database.
        Input args: /id/.
        Output keys: Users/User {id, pw_hash, username}.
    """
    return UserBp().users(user_id=user_id)


@user.route('/users_table/', methods=['GET'])
def users_table():
    return UserBp().users_table()

microcontrollers-rest-api/app/blueprints/user/templates/user/register.html
{% extends "base.html" %}

{% block body %}
    <div class="center">
        <h1 class="center"> Create an account </h1>
        <form action="{{url_for('user.register')}}" method='POST'>
            <div>
                <label for='login'></label><input class="white_text" type='text' name='login' id='login' placeholder='login'/>
            </div>
            <div>
                <label for='password'></label><input class="white_text" type='password' name='password' id='password' placeholder='password'/>
            </div>
            <div>
                <label for='repeat_password'></label><input class="white_text" type='password' name='repeat_password' id='repeat_password' placeholder='repeat password'/>
            </div>
            <div>
                <input class="button" type='submit' name='submit'/>
            </div>
        </form>
    </div>
{% endblock %}

microcontrollers-rest-api/app/blueprints/user/templates/user/users_table.html
{% extends "table_base.html" %}

            {% block title %}
                Users
            {% endblock %}
            {%  block table_heading %}
                        <th onclick="sortTable(0)">ID</th>
                        <th onclick="sortTable(1)">USERNAME</th>
                        <th onclick="sortTable(2)">PW_HASH</th>
            {% endblock %}

            {% block url %}
                '{{ url_for('user.users') }}'
            {% endblock %}
            {% block for_each %}
                data = data.users
                data.forEach(item => {
                        const row = tableBody.insertRow();
                        const cell1 = row.insertCell(0);
                        const cell2 = row.insertCell(1);
                        const cell3 = row.insertCell(2);

                        cell1.textContent = item.id;
                        cell2.textContent = item.username;
                        cell3.textContent = item.pw_hash;
                });
            {% endblock %}

{% block body %}
    {{ super() }}
{% endblock %}