rest-api/app/blueprints/params/__init__.py
from flask import Blueprint

params = Blueprint('params',
                   __name__,
                   # url_prefix='/params',
                   template_folder='templates')

from app.blueprints.params import views

rest-api/app/blueprints/params/views.py
import flask_login

from app.blueprints.params import params as bp_params
from app.blueprints.params.params_bp import ParamsBp


@bp_params.route('/params/<int:params_id>/', methods=['GET'])
@bp_params.route('/params/', methods=['GET'])
def params(params_id: int = None):
    """ Returns params with given id or if not specified list of all params from database.
        If given timestamp, returns list of params with later timestamp.
        Input args: /id/, Timestamp.
        Output keys: performance {id, cpu_usage, disk_usage, memory_usage}
    """
    return ParamsBp().params(params_id=params_id)


@bp_params.route('/add_params/', methods=['POST'])
def add_params():
    """ POST method.
        Adds params to database.
        Input args: MemoryUsage, CpuUsage, DiskUsage.
    """
    return ParamsBp().add_params()


@bp_params.route('/delete_params/', methods=['DELETE'])
@bp_params.route('/delete_params/<int:params_id>/', methods=['DELETE'])
def delete_params(params_id: int = None):
    """ DELETE method.
        Delete params with given id or if given timestamp, deletes params with earlier timestamp.
        Input args: /id/, Timestamp.
    """
    return ParamsBp().delete_params(params_id=params_id)


@bp_params.route('/update_params/<int:params_id>/', methods=['PUT'])
def update_params(params_id: int = None):
    """ PUT method.
        Updates params with given id.
        Input args: MemoryUsage, CpuUsage, DiskUsage.
    """
    return ParamsBp().update_params(params_id=params_id)


@bp_params.route('/performance/', methods=['GET'])
def performance():
    """ Collects computer performance data.
        Output keys: cpu: {usage, freq}, disk: {usage, total, used, free}, virtual_memory: {total, free, available, used}.
    """
    return ParamsBp().performance()


@bp_params.route('/params_table/', methods=['GET'])
def params_table():
    return ParamsBp().params_table()


@bp_params.route('/stats/', methods=['GET'])
def stats():
    return ParamsBp().stats()

rest-api/app/blueprints/params/templates/params/params_table.html
{% extends "table_base.html" %}

            {% block title %}
                Params
            {% endblock %}
            {%  block table_heading %}
                        <th onclick="sortTable(0)">ID</th>
                        <th onclick="sortTable(1)">TIMESTAMP</th>
                        <th onclick="sortTable(2)">CPU_USAGE</th>
                        <th onclick="sortTable(3)">MEMORY_USAGE</th>
                        <th onclick="sortTable(4)">DISK_USAGE</th>
            {% endblock %}

            {% block url %}
                '{{ url_for('params.params') }}'
            {% endblock %}
            {% block for_each %}
                data = data.performance
                data.forEach(item => {
                        const row = tableBody.insertRow();
                        const cell1 = row.insertCell(0);
                        const cell2 = row.insertCell(1);
                        const cell3 = row.insertCell(2);
                        const cell4 = row.insertCell(3);
                        const cell5 = row.insertCell(4);

                        cell1.textContent = item.id;
                        cell2.textContent = item.timestamp;
                        cell3.textContent = item.cpu_usage;
                        cell4.textContent = item.memory_usage;
                        cell5.textContent = item.disk_usage;
                });
            {% endblock %}

{% block body %}
    {{ super() }}
{% endblock %}

rest-api/app/blueprints/params/templates/params/stats.html
{% extends "base.html" %}

{% block body %}
     <script>
      function getData() {
        fetch("{{url_for('params.performance')}}")
          .then(response => response.json())
          .then(data => {
             const container = document.getElementById('data-container');
             const cpu = data["cpu"]
             const disk = data["disk"]
             const virtual = data["virtual_memory"]
            container.innerHTML = `
            <div class="white_text">
                <li>
                    <h3>CPU:  </h3>
                    <p>Usage: ${cpu["usage"]}</p>
                    <p>Freq: ${cpu["freq"]}</p>
                </li>
                <li>
                    <h3>Disk:  </h3>
                    <p>Usage: ${disk["usage"]}</p>
                    <p>Total: ${disk["total"]}</p>
                    <p>Free: ${disk["free"]}</p>
                    <p>Used: ${disk["used"]}</p>
                </li>
                <li>
                    <h3>Virtual memory:  </h3>
                    <p>Usage: ${virtual["usage"]}</p>
                    <p>Total: ${virtual["total"]}</p>
                    <p>Available: ${virtual["available"]}</p>
                    <p>Used: ${virtual["used"]}</p>
                </li>
            </div>
              `;
          })
          .catch(error => {
            console.error(error);
          });
      }
      getData();
      setInterval(function() {
        getData();
      }, 500);
    </script>

    <h1> Performance </h1>
    <ul id="data-container"></ul>
{% endblock %}